sudo: required
services:
  - docker

before_install:
  - docker build -t jagadishmadhu/docker-react -f Dockerfile.dev .

script:
  - docker run jagadishmadhu/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-336242118500"
  bucker_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
