sudo: required
services:
  - docker

before_install:
  - gem install bundler
  - docker build -t jagadishmadhu/docker-react -f Dockerfile .

script:
  - docker run jagaishmadhu/docker-react npm run test -- --coverage
